name: Release on Commit to Main

on:
  push:
    branches: [master]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Create tag from commit
        id: create_tag
        run: |
          VERSION="build-$(date +%s)"
          git tag $VERSION
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: target/release/yt_dl_service
